config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :orders
  
  
  resources :categories
  
  
  devise_for :users do
    resources:orders
  end
  
  get '/checkout', to: 'cart#createOrder'
  
  get '/paid', to: 'static_pages#paid'
  
  
  get 'cart/index'
  
  

  resources :movies
  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  
  get '/login', to: 'user#login'
  
  get '/logout', to: 'user#logout'
  
  get '/admins/sign_in', to: 'admins#sign_in'
  
  get '/admins/sign_out', to: 'admins#sign_out'
  
  
  
  
  get '/cart', to: 'cart#index'
  #allow user to call the add method from the URL with a button click
  get '/cart/:id', to: 'cart#add'
  
  
  get 'cart/remove/:id', to: 'cart#remove'
  
  get 'clearCart/', to: 'cart#clearCart'
  
  post '/search', to: 'movies#search'
  
  root :to => 'site#home'
  
  
  get 'category/:title', to:'static_pages#category'
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  def order_params
    params.required(:order).permit(:order_date, :user_id, :status)    
  end
  
  has_many:orderitems
  belongs_to:user
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @user = User.find(current_user.id)
    @orders = @user.orders.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @orderitems = Orderitem.where(order_id: params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_date, :user_id, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_date %>
    <%= form.datetime_select :order_date, id: :order_order_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :order_user_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :order_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order date</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_date %></td>
        <td><%= order.user %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
  <div id= "movieContainer" >
    
    <h1>Order Details</h1>
    
    <table id="customers">
      <tr>
        <td><%= @order.order_date %></td>
        <td><%= @order.user.email %></td>
        <td><%= @order.status %></td>
      </tr>

  
      <tr>
        <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_order_path(@order) %></td>
        <% end %>
        <td><%= link_to 'Back', orders_path %></td>
        
        
        <td></td>
    </tr>
  
   </table>
   
<h1>Order Items</h1>
  <table id="customers">
    <% @orderitems.each do |orderitem| %>
    <tr>
      <td>
        <%= orderitem.title %>
      </td>
      <td>
        <%= orderitem.quantity %>
        </td>
    </tr>
    <% end %>
  </table>
   
  </div>