config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :orders
  
  
  resources :categories
  
  
  devise_for :users do
    resources:orders
  end
  
  get '/checkout', to: 'cart#createOrder'
  
  get '/paid', to: 'static_pages#paid'
  
  
  get 'cart/index'
  
  

  resources :movies
  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  
  get '/login', to: 'user#login'
  
  get '/logout', to: 'user#logout'
  
  get '/admins/sign_in', to: 'admins#sign_in'
  
  get '/admins/sign_out', to: 'admins#sign_out'
  
  
  
  
  get '/cart', to: 'cart#index'
  #allow user to call the add method from the URL with a button click
  get '/cart/:id', to: 'cart#add'
  
  
  get 'cart/remove/:id', to: 'cart#remove'
  
  get 'clearCart/', to: 'cart#clearCart'
  
  post '/search', to: 'movies#search'
  
  root :to => 'site#home'
  
  
  get 'category/:title', to:'static_pages#category'
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_categories.html.erb
<h1>Choose A Genre</h1>


    
    <% @categories.each do |category| %>
    <div class="movieHols">
        
        <h1><%= category.title %></h1>
        <%= link_to (image_tag category.image, :class => "movieHolsIm"), category %>
        <p><%= category.description %></p>
        <p><a href="/category/<%= category.title %>"><%= category.title %></a></p>
        
    </div>

    <% end %>

app/views/layouts/_footer.html.erb
<footer class="foot">
<% if user_signed_in? %>
<%= link_to 'Your Orders', orders_path, :class => "button", :role => "button" %>
<% end %>

<% if admin_signed_in? %>
<%= link_to 'New Category', new_category_path, :class => "button", :role=>"button"%>
<% end %>
</footer>

app/views/layouts/_header.html.erb
    <header class="headSec">
      <%= image_tag("FlicsPlex_logo_Medium.png", alt: "FlicsPlex Logo", :class => "FlicsPlexLogo") %>
      <h1>FlicsPlex</h1>
      <ul>
        <li><%= link_to "Home", root_path %></li>

       
        <% if user_signed_in? %>
        <li><%= link_to"Movies", movies_path %></li>
        <!--<li><%= link_to"Old Sign Out", logout_path %></li>-->
        <li><%= link_to"Cart", cart_path %></li>
        <% else %>
        <!--<li><%= link_to"Old Sign In", login_path %></li>-->
        <% end %>
        
        <% if admin_signed_in? %>
        <li><%= link_to"Movies", movies_path %></li>
        <% end %>
        
        <li><%= link_to "About", about_path %></li>
        <!--<li><%= link_to "Help", help_path %></li>-->
        
        <!--devise login-->
        
        <% if user_signed_in? %>
        
        <li><a href = '#'>Hi <%= current_user.email %></a></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
        
        <% else %>
        
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        
        
        <% if admin_signed_in? %>
        <li><%= link_to 'Admin Sign Out', destroy_admin_session_path, :method => :delete %> </li>
        <% else %>
        <li><%= link_to 'Admin Sign In', new_admin_session_path %> </li>
        <% end %>
        

        
        <% end %>
        
      </ul>
    </header>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:srcbx, "Search for a Movie") %>
<%= text_field_tag(:srcbx) %>
<%= submit_tag("Search") %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Best Movie Site in the WORLD!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    
    <div class = "container">
      <%= yield %>    
    </div>
    
    <%= render 'layouts/footer' %>


  </body>
</html>